services:
  postgres:
    image: postgres:latest
    container_name: bankdb
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
