version: '3'

networks:
  db-network:
    driver: bridge

services:
  postgres:
    image: postgres:14.4
    container_name: db
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=root
    networks:
      - db-network

  api:
    restart: always
    build: api
    container_name: api
    ports:
      - "8080:8080"
    networks:
      - db-network
